name:                icfpc2024
version:             0.1.0.0
github:              "githubuser/icfpc2024"
license:             BSD-3-Clause
author:              "Serge Ivanov"
maintainer:          "lutvuk@gmail.com"
copyright:           "2024 Serge Ivanov"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iSerge/icfpc2024#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - parsec
  - text
  - MissingH
  - http-client
  - http-client-tls
  - http-types
  - utf8-string
  - bytestring

executables:
  icfpc2024-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024
    - linenoise
    - text
    - mtl

tests:
  icfpc2024-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - tasty-quickcheck
